project_id = "qrosfbyafhgrwamagrgn"

[functions.auto-release]
verify_jwt = false

[functions.test-ai-connection]
verify_jwt = false

[functions.ai-builder]
verify_jwt = false

[functions.github-push]
verify_jwt = false

[functions.generate-code]
verify_jwt = false

[functions.ai-builder-agents]
verify_jwt = false

[functions.generate-brand]
verify_jwt = false

[functions.marketplace-api]
verify_jwt = false

[functions.ai-chat-qa]
verify_jwt = false
