import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Github, Download, Rocket, FolderDown,
  CheckCircle2, Loader2, Copy, Terminal,
  Shield, ExternalLink, Globe,
} from "lucide-react";
import { useState } from "react";
import { cn } from "@/lib/utils";
import { toast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import type { AppConfig } from "@/lib/engine";
import { generateProjectCode } from "@/lib/engine/code-generator";
import { exportToHTML } from "@/lib/engine/html-exporter";
import JSZip from "jszip";

interface DeployPanelProps {
  config: AppConfig | null;
  sql?: string;
  onExportJSON: () => void;
  onExportSQL: () => void;
}

type DeployMethod = "github" | "download" | "local" | "approval";

export function DeployPanel({ config, sql, onExportJSON, onExportSQL }: DeployPanelProps) {
  const { user } = useAuth();
  const [selectedMethod, setSelectedMethod] = useState<DeployMethod | null>(null);
  const [githubRepo, setGithubRepo] = useState("");
  const [isDeploying, setIsDeploying] = useState(false);
  const [deployStatus, setDeployStatus] = useState<"idle" | "success" | "error">("idle");
  const [githubUrl, setGithubUrl] = useState("");
  const [isSubmittingApproval, setIsSubmittingApproval] = useState(false);
  const [isExportingHTML, setIsExportingHTML] = useState(false);
  const [htmlExportProgress, setHtmlExportProgress] = useState("");

  if (!config) {
    return (
      <div className="h-full flex items-center justify-center p-6">
        <div className="text-center space-y-3">
          <div className="w-16 h-16 mx-auto rounded-2xl bg-primary/10 flex items-center justify-center">
            <Rocket className="w-7 h-7 text-primary" />
          </div>
          <h3 className="text-lg font-semibold text-foreground">Deploy</h3>
          <p className="text-sm text-muted-foreground max-w-sm">
            Build something first, then deploy via GitHub, download, or local setup.
          </p>
        </div>
      </div>
    );
  }

  const methods = [
    {
      id: "github" as const,
      icon: Github,
      title: "Push to GitHub",
      desc: "Push config and schema to a GitHub repository",
      badge: "Recommended",
    },
    {
      id: "download" as const,
      icon: FolderDown,
      title: "Download Project",
      desc: "Download config JSON, SQL schema, and setup files",
      badge: null,
    },
    {
      id: "approval" as const,
      icon: Shield,
      title: "Submit for Approval",
      desc: "Send configuration for team review before deploying",
      badge: "New",
    },
    {
      id: "local" as const,
      icon: Terminal,
      title: "Local Deploy",
      desc: "Get CLI commands to set up and run locally",
      badge: null,
    },
  ];

  const handleGitHubPush = async () => {
    if (!githubRepo.trim()) {
      toast({ title: "Repository required", description: "Enter a GitHub repository name.", variant: "destructive" });
      return;
    }
    setIsDeploying(true);
    setDeployStatus("idle");

    try {
      const { data, error } = await supabase.functions.invoke("github-push", {
        body: {
          repo: githubRepo,
          config: JSON.stringify({
            _meta: { generator: "RyaanCMS AI Builder", version: "1.0.0", generated_at: new Date().toISOString() },
            config,
          }, null, 2),
          sql: sql || "",
          readme: `# ${config.title}\n\n${config.description}\n\nGenerated by **RyaanCMS AI Builder**.\n\n## Setup\n\n1. Apply database: \`psql -f schema.sql\`\n2. Configure your environment\n3. Import \`config.json\` into RyaanCMS`,
        },
      });

      if (error) throw new Error(error.message);
      if (!data?.success) throw new Error(data?.error || "Push failed");

      setDeployStatus("success");
      setGithubUrl(data.url);
      toast({ title: "Pushed to GitHub!", description: `Files pushed to ${data.repo}` });
    } catch (err: any) {
      setDeployStatus("error");
      toast({ title: "Push failed", description: err.message, variant: "destructive" });
    } finally {
      setIsDeploying(false);
    }
  };

  const handleDownloadZip = async () => {
    try {
      // Generate real source code from config
      const project = generateProjectCode(config, sql || "");
      const zip = new JSZip();

      for (const file of project.files) {
        zip.file(file.path, file.content);
      }

      // Also include raw config.json
      zip.file("config.json", JSON.stringify({
        _meta: { generator: "RyaanCMS AI Builder", version: "2.0.0", generated_at: new Date().toISOString() },
        config,
      }, null, 2));

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${config.title?.toLowerCase().replace(/\s+/g, "-") || "project"}-source.zip`;
      a.click();
      URL.revokeObjectURL(url);

      toast({
        title: "🎉 Source Code Downloaded!",
        description: `${project.summary.total_files} files generated (${project.summary.frontend_files} frontend, ${project.summary.backend_files} backend).`,
      });
    } catch (err: any) {
      toast({ title: "Download failed", description: err.message, variant: "destructive" });
    }
  };

  const handleSubmitApproval = async () => {
    if (!user) return;
    setIsSubmittingApproval(true);
    try {
      const { error } = await supabase.from("deploy_approvals").insert({
        user_id: user.id,
        project_title: config.title || "Untitled Project",
        config: config as any,
        schema_sql: sql || null,
        status: "pending",
      });
      if (error) throw error;
      toast({ title: "Submitted for approval!", description: "Your configuration is pending review." });
    } catch (err: any) {
      toast({ title: "Failed to submit", description: err.message, variant: "destructive" });
    } finally {
      setIsSubmittingApproval(false);
    }
  };

  const localCommands = [
    `# 1. Create project directory`,
    `mkdir ${config.title?.toLowerCase().replace(/\s+/g, "-") || "my-project"} && cd $_`,
    ``,
    `# 2. Initialize with RyaanCMS CLI`,
    `npx ryaancms init --config ./config.json`,
    ``,
    `# 3. Apply database migrations`,
    `npx ryaancms db:migrate --sql ./schema.sql`,
    ``,
    `# 4. Start development server`,
    `npm run dev`,
  ].join("\n");

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({ title: "Copied!", description: "Commands copied to clipboard." });
  };

  return (
    <ScrollArea className="h-full">
      <div className="p-4 space-y-4">
        <div>
          <h3 className="text-sm font-semibold text-foreground">Deploy {config.title}</h3>
          <p className="text-xs text-muted-foreground mt-0.5">Choose a deployment method for your generated project.</p>
        </div>

        {/* Method selector */}
        <div className="grid gap-2">
          {methods.map((m) => (
            <button
              key={m.id}
              onClick={() => setSelectedMethod(m.id)}
              className={cn(
                "flex items-start gap-3 p-3 rounded-xl border text-left transition-all",
                selectedMethod === m.id
                  ? "border-primary bg-primary/5 ring-1 ring-primary"
                  : "border-border bg-card hover:border-primary/30"
              )}
            >
              <div className={cn(
                "w-9 h-9 rounded-lg flex items-center justify-center shrink-0",
                selectedMethod === m.id ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"
              )}>
                <m.icon className="w-4 h-4" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium text-foreground">{m.title}</span>
                  {m.badge && <Badge variant="secondary" className="text-[10px] h-4">{m.badge}</Badge>}
                </div>
                <p className="text-xs text-muted-foreground mt-0.5">{m.desc}</p>
              </div>
            </button>
          ))}
        </div>

        <Separator />

        {/* GitHub Push */}
        {selectedMethod === "github" && (
          <div className="space-y-3">
            <h4 className="text-sm font-medium text-foreground flex items-center gap-2">
              <Github className="w-4 h-4" /> Push to GitHub
            </h4>
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-foreground">Repository</label>
              <Input
                placeholder="owner/repository-name"
                value={githubRepo}
                onChange={(e) => setGithubRepo(e.target.value)}
                className="h-8 text-xs"
              />
              <p className="text-[10px] text-muted-foreground">
                Uses the configured GITHUB_TOKEN. Creates repo if it doesn't exist.
              </p>
            </div>
            <div className="rounded-lg border border-border p-3 space-y-1.5 bg-muted/30">
              <p className="text-xs font-medium text-foreground">Files to push:</p>
              <div className="space-y-1">
                {["config.json", "schema.sql", "README.md", ".ryaancms/metadata.json"].map((f) => (
                  <div key={f} className="flex items-center gap-2 text-xs text-muted-foreground">
                    <div className="w-1.5 h-1.5 rounded-full bg-primary" />
                    <code className="font-mono">{f}</code>
                  </div>
                ))}
              </div>
            </div>
            <Button onClick={handleGitHubPush} disabled={isDeploying} className="w-full gap-2" size="sm">
              {isDeploying ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Github className="w-3.5 h-3.5" />}
              {isDeploying ? "Pushing..." : "Push to GitHub"}
            </Button>
            {deployStatus === "success" && (
              <div className="flex items-center gap-2 p-2 rounded-lg bg-primary/5 border border-primary/20">
                <CheckCircle2 className="w-4 h-4 text-primary" />
                <span className="text-xs text-primary font-medium flex-1">Pushed to {githubRepo}</span>
                {githubUrl && (
                  <a href={githubUrl} target="_blank" rel="noopener noreferrer" className="text-xs text-primary hover:underline flex items-center gap-1">
                    Open <ExternalLink className="w-3 h-3" />
                  </a>
                )}
              </div>
            )}
          </div>
        )}

        {/* Download */}
        {selectedMethod === "download" && (
          <div className="space-y-3">
            <h4 className="text-sm font-medium text-foreground flex items-center gap-2">
              <FolderDown className="w-4 h-4" /> Download Project
            </h4>
            <p className="text-xs text-muted-foreground">Choose a format to download your project.</p>

            {/* HTML */}
            <button
              onClick={async () => {
                if (!config) return;
                setIsExportingHTML(true);
                setHtmlExportProgress("");
                try {
                  const result = await exportToHTML(config, setHtmlExportProgress);
                  const url = URL.createObjectURL(result.blob);
                  const a = document.createElement("a");
                  a.href = url;
                  a.download = result.filename;
                  a.click();
                  URL.revokeObjectURL(url);
                  toast({
                    title: "🌐 HTML Downloaded!",
                    description: `${result.pageCount} page(s), ${result.imageCount} image(s) with inline editor.`,
                  });
                } catch (err: any) {
                  toast({ title: "Export failed", description: err.message, variant: "destructive" });
                } finally {
                  setIsExportingHTML(false);
                  setHtmlExportProgress("");
                }
              }}
              disabled={isExportingHTML}
              className="flex items-start gap-3 w-full p-3 rounded-xl border border-border bg-card hover:border-primary/30 text-left transition-all"
            >
              <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                {isExportingHTML ? <Loader2 className="w-4 h-4 text-primary animate-spin" /> : <Globe className="w-4 h-4 text-primary" />}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium text-foreground">HTML</span>
                  <Badge variant="secondary" className="text-[10px] h-4">+ Editor</Badge>
                </div>
                <p className="text-xs text-muted-foreground mt-0.5">
                  {isExportingHTML && htmlExportProgress ? htmlExportProgress : "Static HTML pages with images & live inline editor. Upload to any server."}
                </p>
              </div>
            </button>

            {/* ZIP (Source Code) */}
            <button
              onClick={handleDownloadZip}
              className="flex items-start gap-3 w-full p-3 rounded-xl border border-border bg-card hover:border-primary/30 text-left transition-all"
            >
              <div className="w-9 h-9 rounded-lg bg-muted flex items-center justify-center shrink-0">
                <FolderDown className="w-4 h-4 text-muted-foreground" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium text-foreground">ZIP</span>
                  <Badge variant="outline" className="text-[10px] h-4">Source Code</Badge>
                </div>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Full React + Node.js project with API, database schema, tests & Docker config.
                </p>
              </div>
            </button>

            {/* JSON */}
            <button
              onClick={onExportJSON}
              className="flex items-start gap-3 w-full p-3 rounded-xl border border-border bg-card hover:border-primary/30 text-left transition-all"
            >
              <div className="w-9 h-9 rounded-lg bg-muted flex items-center justify-center shrink-0">
                <Download className="w-4 h-4 text-muted-foreground" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium text-foreground">JSON</span>
                  <Badge variant="outline" className="text-[10px] h-4">Config</Badge>
                </div>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Raw app configuration file. Import into RyaanCMS or use with the CLI.
                </p>
              </div>
            </button>
          </div>
        )}

        {/* Submit for Approval */}
        {selectedMethod === "approval" && (
          <div className="space-y-3">
            <h4 className="text-sm font-medium text-foreground flex items-center gap-2">
              <Shield className="w-4 h-4" /> Submit for Approval
            </h4>
            <p className="text-xs text-muted-foreground">
              Submit this configuration for team review. It will appear in the Approvals dashboard where it can be reviewed, approved, or rejected before deployment.
            </p>
            <div className="rounded-lg border border-border p-3 space-y-1.5 bg-muted/30">
              <p className="text-xs font-medium text-foreground">What's included:</p>
              <div className="space-y-1 text-xs text-muted-foreground">
                <div className="flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-primary" /> Full app configuration</div>
                <div className="flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-primary" /> Database SQL schema</div>
                <div className="flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-primary" /> Security validation results</div>
              </div>
            </div>
            <Button onClick={handleSubmitApproval} disabled={isSubmittingApproval} className="w-full gap-2" size="sm">
              {isSubmittingApproval ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Shield className="w-3.5 h-3.5" />}
              {isSubmittingApproval ? "Submitting..." : "Submit for Review"}
            </Button>
          </div>
        )}

        {/* Local Deploy */}
        {selectedMethod === "local" && (
          <div className="space-y-3">
            <h4 className="text-sm font-medium text-foreground flex items-center gap-2">
              <Terminal className="w-4 h-4" /> Local Setup Commands
            </h4>
            <div className="relative">
              <pre className="rounded-lg border border-border bg-muted/50 p-3 text-xs font-mono text-foreground whitespace-pre overflow-x-auto">
                {localCommands}
              </pre>
              <Button variant="ghost" size="icon" className="absolute top-2 right-2 h-6 w-6" onClick={() => copyToClipboard(localCommands)}>
                <Copy className="w-3 h-3" />
              </Button>
            </div>
            <div className="rounded-lg border border-border p-3 space-y-1.5 bg-muted/30">
              <p className="text-xs font-medium text-foreground">Prerequisites:</p>
              <ul className="space-y-1 text-xs text-muted-foreground">
                <li className="flex items-center gap-1.5">• Node.js 18+ installed</li>
                <li className="flex items-center gap-1.5">• PostgreSQL running locally</li>
                <li className="flex items-center gap-1.5">• Download config.json and schema.sql first</li>
              </ul>
            </div>
            <Button variant="outline" onClick={handleDownloadZip} className="w-full gap-2" size="sm">
              <Download className="w-3.5 h-3.5" /> Download Files First
            </Button>
          </div>
        )}
      </div>
    </ScrollArea>
  );
}
