// ============================================================
// Engine 9: Source Code Generator
// Converts AppConfig into real React + Express + Prisma files
// ============================================================

import type { AppConfig, PageConfig, ComponentConfig, CollectionConfig, CollectionField, RoleConfig } from "./component-registry";

export interface GeneratedFile {
  path: string;
  content: string;
  language: string;
}

export interface GeneratedProject {
  files: GeneratedFile[];
  summary: {
    total_files: number;
    frontend_files: number;
    backend_files: number;
    config_files: number;
  };
}

// ─── Main Generator ─────────────────────────────────────────

export function generateProjectCode(config: AppConfig, sql: string): GeneratedProject {
  const files: GeneratedFile[] = [];

  // 1. Config / Root files
  files.push(...generateRootFiles(config));

  // 2. Frontend: React + Tailwind
  files.push(...generateFrontendFiles(config));

  // 3. Backend: Express + Prisma
  files.push(...generateBackendFiles(config));

  // 4. Database
  files.push({ path: "database/schema.sql", content: sql || "-- No schema generated", language: "sql" });
  files.push({ path: "database/prisma/schema.prisma", content: generatePrismaSchema(config), language: "prisma" });

  // 5. Docker & CI
  files.push(...generateInfraFiles(config));

  const frontend = files.filter(f => f.path.startsWith("frontend/")).length;
  const backend = files.filter(f => f.path.startsWith("backend/")).length;

  return {
    files,
    summary: {
      total_files: files.length,
      frontend_files: frontend,
      backend_files: backend,
      config_files: files.length - frontend - backend,
    },
  };
}

// ─── Root Files ──────────────────────────────────────────────

function generateRootFiles(config: AppConfig): GeneratedFile[] {
  return [
    {
      path: "README.md",
      content: `# ${config.title}

${config.description}

## Tech Stack

- **Frontend:** React 18 + Vite + Tailwind CSS
- **Backend:** Node.js + Express + Prisma
- **Database:** PostgreSQL with RLS
- **Auth:** JWT-based with role-based access

## Quick Start

\`\`\`bash
# Install dependencies
cd frontend && npm install
cd ../backend && npm install

# Setup database
cd ../database && psql -f schema.sql

# Generate Prisma client
cd ../backend && npx prisma generate

# Start development
cd ../frontend && npm run dev   # Port 5173
cd ../backend && npm run dev    # Port 3001
\`\`\`

## Project Structure

\`\`\`
├── frontend/          # React + Vite app
│   ├── src/
│   │   ├── components/  # UI components
│   │   ├── pages/       # Route pages
│   │   ├── hooks/       # Custom hooks
│   │   ├── lib/         # Utilities
│   │   └── types/       # TypeScript types
├── backend/           # Express API
│   ├── src/
│   │   ├── routes/      # API routes
│   │   ├── middleware/   # Auth, validation
│   │   ├── controllers/ # Business logic
│   │   └── services/    # Data access
├── database/          # SQL + Prisma
│   ├── schema.sql
│   └── prisma/
└── docker-compose.yml
\`\`\`

## Modules

${config.modules.map(m => `- ${m}`).join("\n")}

## Roles

${(config.roles || []).map(r => `- **${r.name}**: ${r.permissions.join(", ")}`).join("\n")}

---
Generated by **RyaanCMS AI Builder**
`,
      language: "markdown",
    },
    {
      path: ".env.example",
      content: `# Database
DATABASE_URL=postgresql://user:password@localhost:5432/${config.title.toLowerCase().replace(/\s+/g, "_")}

# JWT
JWT_SECRET=your-jwt-secret-here
JWT_EXPIRES_IN=7d

# Server
PORT=3001
NODE_ENV=development

# Frontend
VITE_API_URL=http://localhost:3001/api
`,
      language: "env",
    },
  ];
}

// ─── Frontend Files ──────────────────────────────────────────

function generateFrontendFiles(config: AppConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const projectSlug = config.title.toLowerCase().replace(/\s+/g, "-");

  // package.json
  files.push({
    path: "frontend/package.json",
    content: JSON.stringify({
      name: `${projectSlug}-frontend`,
      private: true,
      version: "1.0.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "tsc && vite build",
        preview: "vite preview",
      },
      dependencies: {
        react: "^18.3.1",
        "react-dom": "^18.3.1",
        "react-router-dom": "^6.30.0",
        "react-hook-form": "^7.61.0",
        "@hookform/resolvers": "^3.10.0",
        zod: "^3.25.0",
        "lucide-react": "^0.462.0",
        "tailwind-merge": "^2.6.0",
        clsx: "^2.1.1",
        "class-variance-authority": "^0.7.1",
        axios: "^1.7.0",
      },
      devDependencies: {
        "@types/react": "^18.3.0",
        "@types/react-dom": "^18.3.0",
        typescript: "^5.6.0",
        vite: "^5.4.0",
        "@vitejs/plugin-react": "^4.3.0",
        tailwindcss: "^3.4.0",
        autoprefixer: "^10.4.0",
        postcss: "^8.4.0",
      },
    }, null, 2),
    language: "json",
  });

  // vite.config
  files.push({
    path: "frontend/vite.config.ts",
    content: `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: { '@': path.resolve(__dirname, './src') },
  },
  server: { port: 5173 },
});
`,
    language: "typescript",
  });

  // tailwind.config
  files.push({
    path: "frontend/tailwind.config.js",
    content: `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '${config.style?.primary_color || "#6366f1"}',
      },
      fontFamily: {
        sans: ['${config.style?.font || "Inter"}', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '${config.style?.border_radius === "none" ? "0" : config.style?.border_radius === "sm" ? "0.25rem" : config.style?.border_radius === "lg" ? "0.75rem" : config.style?.border_radius === "full" ? "9999px" : "0.5rem"}',
      },
    },
  },
  plugins: [],
};
`,
    language: "javascript",
  });

  // index.html
  files.push({
    path: "frontend/index.html",
    content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${config.title}</title>
  <meta name="description" content="${config.description}" />
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.tsx"></script>
</body>
</html>
`,
    language: "html",
  });

  // main.tsx
  files.push({
    path: "frontend/src/main.tsx",
    content: `import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);
`,
    language: "tsx",
  });

  // index.css
  files.push({
    path: "frontend/src/index.css",
    content: `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: '${config.style?.font || "Inter"}', sans-serif;
}
`,
    language: "css",
  });

  // Types
  files.push({
    path: "frontend/src/types/index.ts",
    content: generateFrontendTypes(config),
    language: "typescript",
  });

  // API client
  files.push({
    path: "frontend/src/lib/api.ts",
    content: `import axios from 'axios';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3001/api';

export const api = axios.create({
  baseURL: API_URL,
  headers: { 'Content-Type': 'application/json' },
});

// Attach JWT token to requests
api.interceptors.request.use((config) => {
  const token = localStorage.getItem('auth_token');
  if (token) config.headers.Authorization = \`Bearer \${token}\`;
  return config;
});

// Handle 401 responses
api.interceptors.response.use(
  (res) => res,
  (err) => {
    if (err.response?.status === 401) {
      localStorage.removeItem('auth_token');
      window.location.href = '/login';
    }
    return Promise.reject(err);
  }
);
`,
    language: "typescript",
  });

  // Auth hook
  files.push({
    path: "frontend/src/hooks/useAuth.ts",
    content: `import { useState, useEffect, useCallback } from 'react';
import { api } from '@/lib/api';

interface User {
  id: string;
  email: string;
  role: string;
}

export function useAuth() {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const token = localStorage.getItem('auth_token');
    if (token) {
      api.get('/auth/me')
        .then(res => setUser(res.data.user))
        .catch(() => localStorage.removeItem('auth_token'))
        .finally(() => setLoading(false));
    } else {
      setLoading(false);
    }
  }, []);

  const login = useCallback(async (email: string, password: string) => {
    const res = await api.post('/auth/login', { email, password });
    localStorage.setItem('auth_token', res.data.token);
    setUser(res.data.user);
    return res.data;
  }, []);

  const signup = useCallback(async (email: string, password: string, name: string) => {
    const res = await api.post('/auth/signup', { email, password, name });
    localStorage.setItem('auth_token', res.data.token);
    setUser(res.data.user);
    return res.data;
  }, []);

  const logout = useCallback(() => {
    localStorage.removeItem('auth_token');
    setUser(null);
  }, []);

  return { user, loading, login, signup, logout };
}
`,
    language: "typescript",
  });

  // App.tsx with routes
  files.push({
    path: "frontend/src/App.tsx",
    content: generateAppComponent(config),
    language: "tsx",
  });

  // Generate page components
  for (const page of config.pages) {
    files.push({
      path: `frontend/src/pages/${pascalCase(page.name)}Page.tsx`,
      content: generatePageComponent(page, config),
      language: "tsx",
    });
  }

  // Generate reusable components for each component type used
  const usedTypes = new Set<string>();
  for (const page of config.pages) {
    for (const comp of page.components) {
      usedTypes.add(comp.type);
    }
  }
  for (const type of usedTypes) {
    files.push({
      path: `frontend/src/components/${pascalCase(type)}.tsx`,
      content: generateReactComponent(type, config),
      language: "tsx",
    });
  }

  // CRUD hooks for each collection
  for (const col of config.collections) {
    files.push({
      path: `frontend/src/hooks/use${pascalCase(col.name)}.ts`,
      content: generateCrudHook(col),
      language: "typescript",
    });
  }

  return files;
}

// ─── Backend Files ───────────────────────────────────────────

function generateBackendFiles(config: AppConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const projectSlug = config.title.toLowerCase().replace(/\s+/g, "-");

  // package.json
  files.push({
    path: "backend/package.json",
    content: JSON.stringify({
      name: `${projectSlug}-backend`,
      version: "1.0.0",
      type: "module",
      scripts: {
        dev: "tsx watch src/server.ts",
        build: "tsc",
        start: "node dist/server.js",
        "db:migrate": "npx prisma migrate dev",
        "db:generate": "npx prisma generate",
      },
      dependencies: {
        express: "^4.21.0",
        cors: "^2.8.5",
        helmet: "^8.0.0",
        jsonwebtoken: "^9.0.2",
        bcryptjs: "^2.4.3",
        "@prisma/client": "^5.22.0",
        zod: "^3.25.0",
        dotenv: "^16.4.0",
        morgan: "^1.10.0",
      },
      devDependencies: {
        typescript: "^5.6.0",
        tsx: "^4.19.0",
        "@types/express": "^5.0.0",
        "@types/cors": "^2.8.17",
        "@types/jsonwebtoken": "^9.0.7",
        "@types/bcryptjs": "^2.4.6",
        "@types/morgan": "^1.9.9",
        prisma: "^5.22.0",
      },
    }, null, 2),
    language: "json",
  });

  // tsconfig
  files.push({
    path: "backend/tsconfig.json",
    content: JSON.stringify({
      compilerOptions: {
        target: "ES2022",
        module: "ESNext",
        moduleResolution: "bundler",
        outDir: "./dist",
        rootDir: "./src",
        strict: true,
        esModuleInterop: true,
        paths: { "@/*": ["./src/*"] },
      },
      include: ["src/**/*"],
    }, null, 2),
    language: "json",
  });

  // server.ts
  files.push({
    path: "backend/src/server.ts",
    content: `import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import dotenv from 'dotenv';
import { authRouter } from './routes/auth';
${config.collections.map(c => `import { ${camelCase(c.name)}Router } from './routes/${c.name.toLowerCase().replace(/\s+/g, "-")}';`).join("\n")}

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(helmet());
app.use(cors({ origin: process.env.FRONTEND_URL || 'http://localhost:5173', credentials: true }));
app.use(morgan('dev'));
app.use(express.json());

// Routes
app.use('/api/auth', authRouter);
${config.collections.map(c => `app.use('/api/${c.name.toLowerCase().replace(/\s+/g, "-")}', ${camelCase(c.name)}Router);`).join("\n")}

// Health check
app.get('/api/health', (_, res) => res.json({ status: 'ok', timestamp: new Date().toISOString() }));

app.listen(PORT, () => {
  console.log(\`🚀 ${config.title} API running on port \${PORT}\`);
});
`,
    language: "typescript",
  });

  // Auth middleware
  files.push({
    path: "backend/src/middleware/auth.ts",
    content: `import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';

export interface AuthRequest extends Request {
  userId?: string;
  userRole?: string;
}

export function authenticate(req: AuthRequest, res: Response, next: NextFunction) {
  const token = req.headers.authorization?.split(' ')[1];
  if (!token) return res.status(401).json({ error: 'Authentication required' });

  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET || 'secret') as any;
    req.userId = decoded.userId;
    req.userRole = decoded.role;
    next();
  } catch {
    return res.status(401).json({ error: 'Invalid token' });
  }
}

export function authorize(...roles: string[]) {
  return (req: AuthRequest, res: Response, next: NextFunction) => {
    if (!roles.includes(req.userRole || '')) {
      return res.status(403).json({ error: 'Insufficient permissions' });
    }
    next();
  };
}
`,
    language: "typescript",
  });

  // Auth routes
  files.push({
    path: "backend/src/routes/auth.ts",
    content: `import { Router } from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { PrismaClient } from '@prisma/client';
import { z } from 'zod';
import { authenticate, AuthRequest } from '../middleware/auth';

const router = Router();
const prisma = new PrismaClient();

const signupSchema = z.object({
  email: z.string().email(),
  password: z.string().min(6),
  name: z.string().min(1),
});

const loginSchema = z.object({
  email: z.string().email(),
  password: z.string(),
});

router.post('/signup', async (req, res) => {
  try {
    const { email, password, name } = signupSchema.parse(req.body);
    const exists = await prisma.user.findUnique({ where: { email } });
    if (exists) return res.status(409).json({ error: 'Email already registered' });

    const hash = await bcrypt.hash(password, 12);
    const user = await prisma.user.create({
      data: { email, password: hash, name, role: 'user' },
    });

    const token = jwt.sign(
      { userId: user.id, role: user.role },
      process.env.JWT_SECRET || 'secret',
      { expiresIn: process.env.JWT_EXPIRES_IN || '7d' }
    );

    res.status(201).json({ token, user: { id: user.id, email: user.email, role: user.role } });
  } catch (err: any) {
    if (err instanceof z.ZodError) return res.status(400).json({ error: err.errors });
    res.status(500).json({ error: 'Signup failed' });
  }
});

router.post('/login', async (req, res) => {
  try {
    const { email, password } = loginSchema.parse(req.body);
    const user = await prisma.user.findUnique({ where: { email } });
    if (!user || !(await bcrypt.compare(password, user.password))) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }

    const token = jwt.sign(
      { userId: user.id, role: user.role },
      process.env.JWT_SECRET || 'secret',
      { expiresIn: process.env.JWT_EXPIRES_IN || '7d' }
    );

    res.json({ token, user: { id: user.id, email: user.email, role: user.role } });
  } catch (err: any) {
    if (err instanceof z.ZodError) return res.status(400).json({ error: err.errors });
    res.status(500).json({ error: 'Login failed' });
  }
});

router.get('/me', authenticate, async (req: AuthRequest, res) => {
  const user = await prisma.user.findUnique({
    where: { id: req.userId },
    select: { id: true, email: true, name: true, role: true },
  });
  if (!user) return res.status(404).json({ error: 'User not found' });
  res.json({ user });
});

export { router as authRouter };
`,
    language: "typescript",
  });

  // CRUD routes for each collection
  for (const col of config.collections) {
    files.push({
      path: `backend/src/routes/${col.name.toLowerCase().replace(/\s+/g, "-")}.ts`,
      content: generateExpressRoute(col, config),
      language: "typescript",
    });
  }

  return files;
}

// ─── Prisma Schema ───────────────────────────────────────────

function generatePrismaSchema(config: AppConfig): string {
  const models: string[] = [];

  // User model (always needed)
  models.push(`model User {
  id        String   @id @default(uuid())
  email     String   @unique
  password  String
  name      String
  role      String   @default("user")
  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @updatedAt @map("updated_at")

  @@map("users")
}`);

  // Collection models
  for (const col of config.collections) {
    const modelName = pascalCase(col.name);
    const fieldLines: string[] = [
      `  id        String   @id @default(uuid())`,
    ];

    if (col.rls) {
      fieldLines.push(`  userId    String   @map("user_id")`);
      fieldLines.push(`  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)`);
    }

    for (const field of col.fields) {
      if (["id", "user_id", "created_at", "updated_at"].includes(field.name)) continue;
      const prismaType = fieldTypeToPrisma(field.type);
      const optional = field.required ? "" : "?";
      const attrs: string[] = [];
      if (field.unique) attrs.push("@unique");
      if (field.default) attrs.push(`@default("${field.default}")`);
      fieldLines.push(`  ${camelCase(field.name).replace(/\s+/g, "")}  ${prismaType}${optional} ${attrs.join(" ")} @map("${field.name.toLowerCase().replace(/\s+/g, "_")}")`);
    }

    fieldLines.push(`  createdAt DateTime @default(now()) @map("created_at")`);
    fieldLines.push(`  updatedAt DateTime @updatedAt @map("updated_at")`);
    if (col.soft_delete) {
      fieldLines.push(`  deletedAt DateTime? @map("deleted_at")`);
    }

    models.push(`model ${modelName} {\n${fieldLines.join("\n")}\n\n  @@map("${col.name.toLowerCase().replace(/\s+/g, "_")}")\n}`);
  }

  return `// Prisma Schema — Generated by RyaanCMS AI Builder
// Project: ${config.title}

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

${models.join("\n\n")}
`;
}

// ─── Infrastructure Files ────────────────────────────────────

function generateInfraFiles(config: AppConfig): GeneratedFile[] {
  const slug = config.title.toLowerCase().replace(/\s+/g, "-");
  return [
    {
      path: "docker-compose.yml",
      content: `version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${slug}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  backend:
    build: ./backend
    ports: ["3001:3001"]
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/${slug}
      JWT_SECRET: change-me-in-production
    depends_on: [db]

  frontend:
    build: ./frontend
    ports: ["5173:5173"]
    environment:
      VITE_API_URL: http://localhost:3001/api

volumes:
  pgdata:
`,
      language: "yaml",
    },
    {
      path: "backend/Dockerfile",
      content: `FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
RUN npm run build
EXPOSE 3001
CMD ["node", "dist/server.js"]
`,
      language: "dockerfile",
    },
    {
      path: "frontend/Dockerfile",
      content: `FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
`,
      language: "dockerfile",
    },
    {
      path: "frontend/nginx.conf",
      content: `server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api {
    proxy_pass http://backend:3001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
`,
      language: "nginx",
    },
    {
      path: ".github/workflows/ci.yml",
      content: `name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend
        run: cd frontend && npm ci

      - name: Build frontend
        run: cd frontend && npm run build

      - name: Install backend
        run: cd backend && npm ci

      - name: Build backend
        run: cd backend && npm run build
`,
      language: "yaml",
    },
  ];
}

// ─── Component Generators ────────────────────────────────────

function generateAppComponent(config: AppConfig): string {
  const imports = config.pages.map(p => `import ${pascalCase(p.name)}Page from './pages/${pascalCase(p.name)}Page';`).join("\n");
  const routes = config.pages.map(p => {
    const route = p.route || `/${p.name.toLowerCase().replace(/\s+/g, "-")}`;
    return `        <Route path="${route}" element={<${pascalCase(p.name)}Page />} />`;
  }).join("\n");

  return `import { Routes, Route } from 'react-router-dom';
${imports}

export default function App() {
  return (
    <div className="min-h-screen bg-gray-50">
      <Routes>
${routes}
        <Route path="*" element={<div className="p-8 text-center"><h1 className="text-2xl font-bold">404 — Page Not Found</h1></div>} />
      </Routes>
    </div>
  );
}
`;
}

function generatePageComponent(page: PageConfig, config: AppConfig): string {
  const componentImports = page.components
    .map(c => pascalCase(c.type))
    .filter((v, i, a) => a.indexOf(v) === i)
    .map(name => `import { ${name} } from '@/components/${name}';`)
    .join("\n");

  const componentJsx = page.components
    .map(c => {
      const propsStr = c.props
        ? Object.entries(c.props).map(([k, v]) => `${k}={${JSON.stringify(v)}}`).join(" ")
        : "";
      return `      <${pascalCase(c.type)} ${propsStr} />`;
    })
    .join("\n");

  const isDashboard = page.layout === "dashboard";

  return `${componentImports}

export default function ${pascalCase(page.name)}Page() {
  return (
    <div className="${isDashboard ? "flex min-h-screen" : ""}">
      ${isDashboard ? '<main className="flex-1 p-6">' : '<main>'}
${componentJsx}
      </main>
    </div>
  );
}
`;
}

function generateReactComponent(type: string, config: AppConfig): string {
  const name = pascalCase(type);

  // Generate meaningful component templates based on type
  const templates: Record<string, string> = {
    hero: `interface HeroProps {
  headline?: string;
  subtitle?: string;
  cta_text?: string;
  cta_link?: string;
}

export function Hero({ headline = "${config.title}", subtitle = "${config.description}", cta_text = "Get Started", cta_link = "/signup" }: HeroProps) {
  return (
    <section className="relative py-20 px-6 text-center bg-gradient-to-br from-primary/10 to-primary/5">
      <div className="max-w-4xl mx-auto space-y-6">
        <h1 className="text-5xl font-bold tracking-tight">{headline}</h1>
        <p className="text-xl text-gray-600 max-w-2xl mx-auto">{subtitle}</p>
        <a href={cta_link} className="inline-flex items-center px-8 py-3 rounded-lg bg-primary text-white font-medium hover:opacity-90 transition">
          {cta_text}
        </a>
      </div>
    </section>
  );
}`,
    navbar: `interface NavbarProps {
  logo_text?: string;
  show_auth_buttons?: boolean;
}

export function Navbar({ logo_text = "${config.title}", show_auth_buttons = true }: NavbarProps) {
  return (
    <header className="sticky top-0 z-50 bg-white/80 backdrop-blur border-b">
      <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
        <a href="/" className="text-xl font-bold">{logo_text}</a>
        <nav className="hidden md:flex items-center gap-6">
          <a href="/" className="text-sm hover:text-primary transition">Home</a>
          <a href="/about" className="text-sm hover:text-primary transition">About</a>
          {show_auth_buttons && (
            <a href="/login" className="px-4 py-2 rounded-lg bg-primary text-white text-sm font-medium hover:opacity-90 transition">
              Sign In
            </a>
          )}
        </nav>
      </div>
    </header>
  );
}`,
    footer: `export function Footer() {
  return (
    <footer className="bg-gray-900 text-gray-400 py-12 px-6">
      <div className="max-w-7xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8">
        <div>
          <h3 className="text-white font-semibold mb-3">${config.title}</h3>
          <p className="text-sm">${config.description}</p>
        </div>
        <div>
          <h4 className="text-white font-medium mb-3">Product</h4>
          <ul className="space-y-2 text-sm">
            <li><a href="#" className="hover:text-white transition">Features</a></li>
            <li><a href="#" className="hover:text-white transition">Pricing</a></li>
          </ul>
        </div>
        <div>
          <h4 className="text-white font-medium mb-3">Company</h4>
          <ul className="space-y-2 text-sm">
            <li><a href="#" className="hover:text-white transition">About</a></li>
            <li><a href="#" className="hover:text-white transition">Contact</a></li>
          </ul>
        </div>
        <div>
          <h4 className="text-white font-medium mb-3">Legal</h4>
          <ul className="space-y-2 text-sm">
            <li><a href="#" className="hover:text-white transition">Privacy</a></li>
            <li><a href="#" className="hover:text-white transition">Terms</a></li>
          </ul>
        </div>
      </div>
      <div className="max-w-7xl mx-auto mt-8 pt-8 border-t border-gray-800 text-sm text-center">
        © {new Date().getFullYear()} ${config.title}. All rights reserved.
      </div>
    </footer>
  );
}`,
    crud_table: `import { useState, useEffect } from 'react';
import { api } from '@/lib/api';

interface CrudTableProps {
  collection?: string;
  columns?: string[];
}

export function CrudTable({ collection = "items", columns = ["id", "name", "created_at"] }: CrudTableProps) {
  const [data, setData] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get(\`/\${collection}\`).then(res => setData(res.data)).finally(() => setLoading(false));
  }, [collection]);

  if (loading) return <div className="p-6 text-center">Loading...</div>;

  return (
    <div className="rounded-lg border bg-white overflow-hidden">
      <table className="w-full text-sm">
        <thead className="bg-gray-50 border-b">
          <tr>
            {columns.map(col => (
              <th key={col} className="px-4 py-3 text-left font-medium text-gray-600 capitalize">{col.replace(/_/g, " ")}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.map((row, i) => (
            <tr key={i} className="border-b last:border-0 hover:bg-gray-50">
              {columns.map(col => (
                <td key={col} className="px-4 py-3 text-gray-700">{String(row[col] ?? "—")}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}`,
    auth_form: `import { useState } from 'react';
import { useAuth } from '@/hooks/useAuth';

interface AuthFormProps {
  mode?: 'login' | 'signup' | 'both';
  redirect_after?: string;
}

export function AuthForm({ mode = 'both', redirect_after = '/dashboard' }: AuthFormProps) {
  const { login, signup } = useAuth();
  const [isLogin, setIsLogin] = useState(mode !== 'signup');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [name, setName] = useState('');
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    try {
      if (isLogin) {
        await login(email, password);
      } else {
        await signup(email, password, name);
      }
      window.location.href = redirect_after;
    } catch (err: any) {
      setError(err.response?.data?.error || 'Something went wrong');
    }
  };

  return (
    <div className="max-w-md mx-auto p-8">
      <h2 className="text-2xl font-bold mb-6">{isLogin ? 'Sign In' : 'Create Account'}</h2>
      <form onSubmit={handleSubmit} className="space-y-4">
        {!isLogin && (
          <input type="text" placeholder="Full Name" value={name} onChange={e => setName(e.target.value)}
            className="w-full px-4 py-2 rounded-lg border focus:ring-2 focus:ring-primary outline-none" required />
        )}
        <input type="email" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)}
          className="w-full px-4 py-2 rounded-lg border focus:ring-2 focus:ring-primary outline-none" required />
        <input type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)}
          className="w-full px-4 py-2 rounded-lg border focus:ring-2 focus:ring-primary outline-none" required />
        {error && <p className="text-red-500 text-sm">{error}</p>}
        <button type="submit" className="w-full py-2 rounded-lg bg-primary text-white font-medium hover:opacity-90 transition">
          {isLogin ? 'Sign In' : 'Sign Up'}
        </button>
      </form>
      {mode === 'both' && (
        <p className="text-sm text-center mt-4 text-gray-500">
          {isLogin ? "Don't have an account?" : "Already have an account?"}
          <button onClick={() => setIsLogin(!isLogin)} className="text-primary ml-1 hover:underline">
            {isLogin ? 'Sign Up' : 'Sign In'}
          </button>
        </p>
      )}
    </div>
  );
}`,
    stats_row: `interface StatsRowProps {
  metrics?: Array<{ label: string; value: string | number; trend?: string }>;
}

export function StatsRow({ metrics = [{ label: "Users", value: "1,234" }, { label: "Revenue", value: "$12.4k" }, { label: "Orders", value: 567 }] }: StatsRowProps) {
  return (
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
      {metrics.map((m, i) => (
        <div key={i} className="bg-white rounded-lg border p-4 space-y-1">
          <p className="text-sm text-gray-500">{m.label}</p>
          <p className="text-2xl font-bold">{m.value}</p>
          {m.trend && <p className="text-xs text-green-600">{m.trend}</p>}
        </div>
      ))}
    </div>
  );
}`,
    card_grid: `interface CardGridProps {
  columns?: number;
}

export function CardGrid({ columns = 3 }: CardGridProps) {
  return (
    <div className={\`grid grid-cols-1 md:grid-cols-\${columns} gap-6 p-6\`}>
      {[1, 2, 3, 4, 5, 6].map(i => (
        <div key={i} className="bg-white rounded-lg border overflow-hidden hover:shadow-md transition">
          <div className="h-48 bg-gray-100" />
          <div className="p-4 space-y-2">
            <h3 className="font-semibold">Card Title {i}</h3>
            <p className="text-sm text-gray-500">Card description goes here.</p>
          </div>
        </div>
      ))}
    </div>
  );
}`,
    form: `import { useState } from 'react';

interface FormProps {
  fields?: Array<{ name: string; type: string; required?: boolean }>;
  submit_label?: string;
}

export function Form({ fields = [{ name: "name", type: "text", required: true }, { name: "email", type: "email", required: true }], submit_label = "Submit" }: FormProps) {
  const [values, setValues] = useState<Record<string, string>>({});

  return (
    <form className="max-w-lg mx-auto space-y-4 p-6" onSubmit={e => { e.preventDefault(); console.log(values); }}>
      {fields.map(f => (
        <div key={f.name} className="space-y-1">
          <label className="text-sm font-medium capitalize">{f.name.replace(/_/g, " ")}</label>
          <input type={f.type || "text"} required={f.required}
            value={values[f.name] || ""}
            onChange={e => setValues(prev => ({ ...prev, [f.name]: e.target.value }))}
            className="w-full px-4 py-2 rounded-lg border focus:ring-2 focus:ring-primary outline-none" />
        </div>
      ))}
      <button type="submit" className="px-6 py-2 rounded-lg bg-primary text-white font-medium hover:opacity-90 transition">
        {submit_label}
      </button>
    </form>
  );
}`,
  };

  if (templates[type]) {
    return templates[type];
  }

  // Fallback generic component
  return `interface ${name}Props {
  [key: string]: any;
}

export function ${name}(props: ${name}Props) {
  return (
    <section className="p-6">
      <div className="max-w-7xl mx-auto">
        <h2 className="text-2xl font-bold mb-4">${name.replace(/([A-Z])/g, ' $1').trim()}</h2>
        <p className="text-gray-500">This component can be customized via props.</p>
      </div>
    </section>
  );
}
`;
}

function generateCrudHook(col: CollectionConfig): string {
  const name = pascalCase(col.name);
  const slug = col.name.toLowerCase().replace(/\s+/g, "-");

  return `import { useState, useEffect, useCallback } from 'react';
import { api } from '@/lib/api';

export function use${name}() {
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetch = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.get('/${slug}');
      setItems(res.data);
      setError(null);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetch(); }, [fetch]);

  const create = async (data: any) => {
    const res = await api.post('/${slug}', data);
    setItems(prev => [...prev, res.data]);
    return res.data;
  };

  const update = async (id: string, data: any) => {
    const res = await api.put(\`/${slug}/\${id}\`, data);
    setItems(prev => prev.map(item => item.id === id ? res.data : item));
    return res.data;
  };

  const remove = async (id: string) => {
    await api.delete(\`/${slug}/\${id}\`);
    setItems(prev => prev.filter(item => item.id !== id));
  };

  return { items, loading, error, fetch, create, update, remove };
}
`;
}

function generateExpressRoute(col: CollectionConfig, config: AppConfig): string {
  const name = pascalCase(col.name);
  const model = camelCase(col.name);
  const slug = col.name.toLowerCase().replace(/\s+/g, "-");

  return `import { Router } from 'express';
import { PrismaClient } from '@prisma/client';
import { authenticate, authorize, AuthRequest } from '../middleware/auth';

const router = Router();
const prisma = new PrismaClient();

// GET /${slug} — List all
router.get('/', ${col.rls ? "authenticate, " : ""}async (req: AuthRequest, res) => {
  try {
    const items = await prisma.${model}.findMany({
      ${col.rls ? "where: { userId: req.userId }," : ""}
      orderBy: { createdAt: 'desc' },
    });
    res.json(items);
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch ${col.name}' });
  }
});

// GET /${slug}/:id — Get one
router.get('/:id', ${col.rls ? "authenticate, " : ""}async (req: AuthRequest, res) => {
  try {
    const item = await prisma.${model}.findFirst({
      where: { id: req.params.id${col.rls ? ", userId: req.userId" : ""} },
    });
    if (!item) return res.status(404).json({ error: 'Not found' });
    res.json(item);
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch ${col.name}' });
  }
});

// POST /${slug} — Create
router.post('/', authenticate, async (req: AuthRequest, res) => {
  try {
    const item = await prisma.${model}.create({
      data: { ...req.body, ${col.rls ? "userId: req.userId!," : ""} },
    });
    res.status(201).json(item);
  } catch (err) {
    res.status(500).json({ error: 'Failed to create ${col.name}' });
  }
});

// PUT /${slug}/:id — Update
router.put('/:id', authenticate, async (req: AuthRequest, res) => {
  try {
    const item = await prisma.${model}.update({
      where: { id: req.params.id },
      data: req.body,
    });
    res.json(item);
  } catch (err) {
    res.status(500).json({ error: 'Failed to update ${col.name}' });
  }
});

// DELETE /${slug}/:id — Delete
router.delete('/:id', authenticate, async (req: AuthRequest, res) => {
  try {
    await prisma.${model}.delete({ where: { id: req.params.id } });
    res.status(204).send();
  } catch (err) {
    res.status(500).json({ error: 'Failed to delete ${col.name}' });
  }
});

export { router as ${camelCase(col.name)}Router };
`;
}

function generateFrontendTypes(config: AppConfig): string {
  const types = config.collections.map(col => {
    const fields = col.fields.map(f => {
      const tsType = fieldTypeToTS(f.type);
      return `  ${camelCase(f.name)}: ${tsType}${f.required ? "" : " | null"};`;
    }).join("\n");

    return `export interface ${pascalCase(col.name)} {
  id: string;
${fields}
  createdAt: string;
  updatedAt: string;
}`;
  }).join("\n\n");

  return `// Auto-generated types from AppConfig\n\n${types}\n`;
}

// ─── Helpers ─────────────────────────────────────────────────

function pascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

function camelCase(str: string): string {
  const pascal = pascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function fieldTypeToTS(type: string): string {
  const map: Record<string, string> = {
    text: "string", number: "number", boolean: "boolean",
    date: "string", timestamp: "string", relation: "string",
    json: "Record<string, any>", media: "string", enum: "string",
    uuid: "string", email: "string", url: "string", password: "string",
  };
  return map[type] || "any";
}

function fieldTypeToPrisma(type: string): string {
  const map: Record<string, string> = {
    text: "String", number: "Float", boolean: "Boolean",
    date: "DateTime", timestamp: "DateTime", relation: "String",
    json: "Json", media: "String", enum: "String",
    uuid: "String", email: "String", url: "String", password: "String",
  };
  return map[type] || "String";
}
