// ============================================================
// HTML Exporter — Converts AppConfig → Static HTML/CSS/JS ZIP
// Produces standalone HTML pages with bundled styles and
// a lightweight inline content editor for live editing.
// ============================================================

import type { AppConfig, PageConfig, ComponentConfig } from "./component-registry";
import JSZip from "jszip";

// ── Image Collector ─────────────────────────────────────────

function collectImageUrls(config: AppConfig): string[] {
  const urls = new Set<string>();
  const walk = (obj: any) => {
    if (!obj || typeof obj !== "object") return;
    for (const [key, val] of Object.entries(obj)) {
      if (typeof val === "string" && /^https?:\/\/.+\.(png|jpe?g|gif|webp|svg|ico|avif|bmp)/i.test(val)) {
        urls.add(val);
      } else if (typeof val === "object") {
        walk(val);
      }
    }
  };
  walk(config);
  return Array.from(urls);
}

async function downloadImages(urls: string[]): Promise<Map<string, { blob: Blob; localPath: string }>> {
  const map = new Map<string, { blob: Blob; localPath: string }>();
  const tasks = urls.map(async (url, i) => {
    try {
      const res = await fetch(url);
      if (!res.ok) return;
      const blob = await res.blob();
      const ext = url.match(/\.(png|jpe?g|gif|webp|svg|ico|avif|bmp)/i)?.[1] || "png";
      const localPath = `images/img-${i + 1}.${ext}`;
      map.set(url, { blob, localPath });
    } catch { /* skip failed downloads */ }
  });
  await Promise.all(tasks);
  return map;
}

function rewriteUrl(url: string, imageMap: Map<string, { blob: Blob; localPath: string }>): string {
  return imageMap.get(url)?.localPath || url;
}

// ── CSS Generator ───────────────────────────────────────────

function generateCSS(config: AppConfig): string {
  const primary = config.style?.primary_color || "#6366f1";
  return `/* Generated by RyaanCMS AI Builder */
:root {
  --primary: ${primary};
  --primary-light: ${primary}22;
  --bg: #ffffff;
  --bg-card: #f9fafb;
  --text: #111827;
  --text-muted: #6b7280;
  --border: #e5e7eb;
  --radius: ${config.style?.border_radius === "lg" ? "12px" : config.style?.border_radius === "sm" ? "4px" : "8px"};
  --font: ${config.style?.font || "'Inter', system-ui, -apple-system, sans-serif"};
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: var(--font); background: var(--bg); color: var(--text); line-height: 1.6; }
a { color: var(--primary); text-decoration: none; }
img { max-width: 100%; height: auto; }

/* Layout */
.container { max-width: 1200px; margin: 0 auto; padding: 0 24px; }
.section { padding: 60px 0; }
.flex { display: flex; }
.flex-col { flex-direction: column; }
.items-center { align-items: center; }
.justify-between { justify-content: space-between; }
.justify-center { justify-content: center; }
.gap-1 { gap: 4px; } .gap-2 { gap: 8px; } .gap-3 { gap: 12px; } .gap-4 { gap: 16px; } .gap-6 { gap: 24px; }
.grid { display: grid; }
.grid-2 { grid-template-columns: repeat(2, 1fr); }
.grid-3 { grid-template-columns: repeat(3, 1fr); }
.grid-4 { grid-template-columns: repeat(4, 1fr); }
.text-center { text-align: center; }
.text-left { text-align: left; }
.w-full { width: 100%; }
.mx-auto { margin-left: auto; margin-right: auto; }
.relative { position: relative; }
.hidden { display: none; }

/* Typography */
h1 { font-size: 2.5rem; font-weight: 800; letter-spacing: -0.025em; line-height: 1.1; }
h2 { font-size: 1.75rem; font-weight: 700; letter-spacing: -0.025em; }
h3 { font-size: 1.125rem; font-weight: 600; }
.text-sm { font-size: 0.875rem; }
.text-xs { font-size: 0.75rem; }
.text-muted { color: var(--text-muted); }
.font-bold { font-weight: 700; }
.font-medium { font-weight: 500; }

/* Components */
.card { background: var(--bg-card); border: 1px solid var(--border); border-radius: var(--radius); padding: 24px; }
.badge { display: inline-flex; align-items: center; gap: 4px; padding: 4px 12px; border-radius: 9999px; font-size: 0.75rem; font-weight: 500; background: var(--primary-light); color: var(--primary); }
.btn { display: inline-flex; align-items: center; gap: 8px; padding: 10px 20px; border-radius: var(--radius); font-size: 0.875rem; font-weight: 600; border: none; cursor: pointer; transition: all 0.2s; }
.btn-primary { background: var(--primary); color: white; }
.btn-primary:hover { opacity: 0.9; transform: translateY(-1px); }
.btn-outline { background: transparent; border: 1px solid var(--border); color: var(--text); }
.btn-outline:hover { background: var(--bg-card); }
.input { width: 100%; padding: 8px 12px; border: 1px solid var(--border); border-radius: var(--radius); font-size: 0.875rem; background: white; color: var(--text); }
.input:focus { outline: none; border-color: var(--primary); box-shadow: 0 0 0 3px var(--primary-light); }

/* Navbar */
.navbar { display: flex; align-items: center; justify-content: space-between; padding: 12px 24px; border-bottom: 1px solid var(--border); background: rgba(255,255,255,0.9); backdrop-filter: blur(8px); position: sticky; top: 0; z-index: 50; }
.nav-logo { display: flex; align-items: center; gap: 8px; font-weight: 700; font-size: 0.875rem; }
.nav-logo-icon { width: 32px; height: 32px; border-radius: 8px; background: var(--primary); display: flex; align-items: center; justify-content: center; color: white; font-weight: 800; font-size: 14px; }
.nav-links { display: flex; align-items: center; gap: 4px; }
.nav-link { padding: 6px 12px; border-radius: 6px; font-size: 0.8rem; font-weight: 500; color: var(--text-muted); transition: all 0.2s; }
.nav-link:hover, .nav-link.active { color: var(--text); background: var(--bg-card); }

/* Hero */
.hero { padding: 80px 24px; text-align: center; background: linear-gradient(135deg, var(--primary-light), white, rgba(168,162,255,0.08)); }
.hero h1 { margin-bottom: 16px; }
.hero p { color: var(--text-muted); max-width: 540px; margin: 0 auto 24px; }
.hero-actions { display: flex; gap: 12px; justify-content: center; }

/* Footer */
.footer { padding: 40px 24px; border-top: 1px solid var(--border); background: var(--bg-card); }
.footer-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 32px; max-width: 1200px; margin: 0 auto; }
.footer-col h4 { font-size: 0.8rem; font-weight: 600; margin-bottom: 12px; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-muted); }
.footer-col a { display: block; font-size: 0.8rem; color: var(--text-muted); padding: 4px 0; transition: color 0.2s; }
.footer-col a:hover { color: var(--primary); }
.footer-bottom { text-align: center; padding-top: 24px; margin-top: 24px; border-top: 1px solid var(--border); font-size: 0.75rem; color: var(--text-muted); }

/* Stats */
.stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; }
.stat-card { background: var(--bg-card); border: 1px solid var(--border); border-radius: var(--radius); padding: 20px; }
.stat-value { font-size: 1.5rem; font-weight: 800; }
.stat-label { font-size: 0.75rem; color: var(--text-muted); }

/* Pricing */
.pricing-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; max-width: 1000px; margin: 0 auto; }
.price-card { border: 1px solid var(--border); border-radius: var(--radius); padding: 32px; text-align: center; }
.price-card.featured { border-color: var(--primary); position: relative; }
.price-amount { font-size: 2.5rem; font-weight: 800; }
.price-period { font-size: 0.8rem; color: var(--text-muted); }
.price-features { list-style: none; text-align: left; margin: 24px 0; }
.price-features li { padding: 6px 0; font-size: 0.8rem; color: var(--text-muted); display: flex; align-items: center; gap: 8px; }
.price-features li::before { content: "✓"; color: var(--primary); font-weight: 700; }

/* FAQ */
.faq-item { border: 1px solid var(--border); border-radius: var(--radius); margin-bottom: 8px; overflow: hidden; }
.faq-question { width: 100%; padding: 16px 20px; display: flex; justify-content: space-between; align-items: center; font-size: 0.875rem; font-weight: 600; background: none; border: none; cursor: pointer; text-align: left; color: var(--text); }
.faq-answer { padding: 0 20px 16px; font-size: 0.8rem; color: var(--text-muted); line-height: 1.7; display: none; }
.faq-item.open .faq-answer { display: block; }

/* Features */
.feature-card { padding: 24px; border: 1px solid var(--border); border-radius: var(--radius); transition: all 0.2s; }
.feature-card:hover { border-color: var(--primary); box-shadow: 0 4px 12px rgba(0,0,0,0.05); }
.feature-icon { width: 48px; height: 48px; border-radius: 12px; background: var(--primary-light); display: flex; align-items: center; justify-content: center; margin-bottom: 16px; color: var(--primary); }

/* Testimonials */
.testimonial-card { padding: 24px; border: 1px solid var(--border); border-radius: var(--radius); }
.testimonial-stars { color: #f59e0b; font-size: 0.875rem; margin-bottom: 12px; }
.testimonial-author { display: flex; align-items: center; gap: 12px; margin-top: 16px; }
.testimonial-avatar { width: 40px; height: 40px; border-radius: 50%; background: var(--primary-light); display: flex; align-items: center; justify-content: center; font-weight: 700; color: var(--primary); font-size: 0.875rem; }

/* CTA */
.cta-section { padding: 64px 24px; background: linear-gradient(135deg, var(--primary), #818cf8); color: white; text-align: center; border-radius: var(--radius); margin: 40px auto; max-width: 900px; }
.cta-section h2 { color: white; }
.cta-section p { color: rgba(255,255,255,0.85); max-width: 500px; margin: 12px auto 24px; }

/* Table */
.data-table { width: 100%; border-collapse: collapse; }
.data-table th { text-align: left; font-size: 0.7rem; font-weight: 600; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.05em; padding: 10px 16px; border-bottom: 1px solid var(--border); background: var(--bg-card); }
.data-table td { padding: 12px 16px; border-bottom: 1px solid var(--border); font-size: 0.8rem; }
.data-table tr:hover { background: rgba(0,0,0,0.02); }

/* Contact form */
.contact-form { max-width: 500px; }
.form-group { margin-bottom: 16px; }
.form-label { display: block; font-size: 0.8rem; font-weight: 500; margin-bottom: 6px; }
textarea.input { min-height: 100px; resize: vertical; }

/* Responsive */
@media (max-width: 768px) {
  h1 { font-size: 1.75rem; }
  h2 { font-size: 1.25rem; }
  .grid-2, .grid-3, .grid-4 { grid-template-columns: 1fr; }
  .stats-grid { grid-template-columns: repeat(2, 1fr); }
  .pricing-grid { grid-template-columns: 1fr; }
  .footer-grid { grid-template-columns: repeat(2, 1fr); }
  .nav-links { display: none; }
  .hero { padding: 48px 16px; }
}

/* Editor styles — hidden by default, only visible when unlocked */
[data-editable] { cursor: default; }
body.editor-unlocked [data-editable]:hover { outline: 2px dashed var(--primary); outline-offset: 2px; cursor: text; }
body.editor-unlocked [data-editable]:focus { outline: 2px solid var(--primary); outline-offset: 2px; background: rgba(99,102,241,0.05); }
.editor-toolbar { position: fixed; top: 0; left: 0; right: 0; z-index: 9999; background: #1f2937; color: white; padding: 8px 16px; display: flex; align-items: center; justify-content: space-between; font-family: var(--font); box-shadow: 0 2px 8px rgba(0,0,0,0.2); }
.editor-toolbar button { background: var(--primary); color: white; border: none; padding: 6px 16px; border-radius: 6px; font-size: 0.8rem; font-weight: 600; cursor: pointer; }
.editor-toolbar button:hover { opacity: 0.9; }
.editor-toolbar .editor-info { font-size: 0.75rem; opacity: 0.7; }
body.editor-active { padding-top: 44px; }
`;
}

// ── Inline Editor JS ────────────────────────────────────────

function generateEditorJS(password: string): string {
  return `// RyaanCMS Inline Editor — password-protected content editing
(function() {
  'use strict';
  var STORAGE_KEY = 'ryaancms_edits';
  var PASS_KEY = 'ryaancms_editor_unlocked';
  var EDITOR_PASSWORD = '${password.replace(/'/g, "\\'")}';
  var edits = {};
  var isUnlocked = sessionStorage.getItem(PASS_KEY) === 'true';

  // Load saved edits
  try {
    edits = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}');
  } catch(e) {}

  // Apply saved edits on load
  function applyEdits() {
    Object.keys(edits).forEach(function(id) {
      var el = document.querySelector('[data-edit-id="' + id + '"]');
      if (el) {
        if (el.tagName === 'IMG') {
          el.src = edits[id];
        } else {
          el.innerHTML = edits[id];
        }
      }
    });
  }

  // Activate editor — only called after successful password
  function initEditor() {
    document.body.classList.add('editor-active');
    document.body.classList.add('editor-unlocked');

    var toolbar = document.createElement('div');
    toolbar.className = 'editor-toolbar';
    toolbar.innerHTML = '<div class="flex items-center gap-3"><span style="font-weight:700;font-size:14px;">✏️ Live Editor</span><span class="editor-info">' + Object.keys(edits).length + ' edits</span></div><div class="flex items-center gap-2"><button onclick="window.__ryaanEditor.save()">💾 Save</button><button onclick="window.__ryaanEditor.download()" style="background:#374151;">⬇ Download</button><button onclick="window.__ryaanEditor.reset()" style="background:#ef4444;">↺ Reset</button><button onclick="window.__ryaanEditor.lock()" style="background:#6b7280;">🔒 Lock</button></div>';
    document.body.prepend(toolbar);

    document.querySelectorAll('[data-editable]').forEach(function(el) {
      if (el.tagName !== 'IMG') {
        el.contentEditable = 'true';
        el.addEventListener('blur', function() {
          var id = el.getAttribute('data-edit-id');
          if (id) {
            edits[id] = el.innerHTML;
            updateCount();
          }
        });
      }
    });

    document.querySelectorAll('img[data-editable]').forEach(function(img) {
      img.style.cursor = 'pointer';
      img.addEventListener('click', function() {
        var input = document.createElement('input');
        input.type = 'file';
        input.accept = 'image/*';
        input.onchange = function(e) {
          var file = e.target.files[0];
          if (!file) return;
          var reader = new FileReader();
          reader.onload = function(ev) {
            img.src = ev.target.result;
            var id = img.getAttribute('data-edit-id');
            if (id) {
              edits[id] = ev.target.result;
              updateCount();
            }
          };
          reader.readAsDataURL(file);
        };
        input.click();
      });
    });
  }

  function updateCount() {
    var info = document.querySelector('.editor-info');
    if (info) info.textContent = Object.keys(edits).length + ' edits';
  }

  window.__ryaanEditor = {
    save: function() {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(edits));
      alert('✅ Changes saved to browser storage!');
    },
    download: function() {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(edits));
      var html = '<!DOCTYPE html>' + document.documentElement.outerHTML;
      var blob = new Blob([html], { type: 'text/html' });
      var a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = (document.title || 'page') + '.html';
      a.click();
      URL.revokeObjectURL(a.href);
    },
    reset: function() {
      if (confirm('Reset all edits? This cannot be undone.')) {
        edits = {};
        localStorage.removeItem(STORAGE_KEY);
        location.reload();
      }
    },
    lock: function() {
      sessionStorage.removeItem(PASS_KEY);
      location.reload();
    },
    unlock: function() {
      var entered = prompt('🔒 Enter editor password:');
      if (entered === EDITOR_PASSWORD) {
        sessionStorage.setItem(PASS_KEY, 'true');
        location.reload();
      } else if (entered !== null) {
        alert('❌ Incorrect password.');
      }
    }
  };

  // Keyboard shortcut: Ctrl+Shift+E to open password prompt
  document.addEventListener('keydown', function(e) {
    if (e.ctrlKey && e.shiftKey && e.key === 'E') {
      e.preventDefault();
      if (!isUnlocked) window.__ryaanEditor.unlock();
    }
  });

  // Init
  document.addEventListener('DOMContentLoaded', function() {
    applyEdits();
    if (isUnlocked) {
      initEditor();
    }
    // No visible UI for visitors — editor is completely hidden
  });
})();
`;
}

// ── Component → HTML Converters ─────────────────────────────

let editCounter = 0;
function eid(): string { return `e-${++editCounter}`; }
function ed(tag: string, content: string, cls?: string): string {
  const id = eid();
  return `<${tag} data-editable data-edit-id="${id}" class="${cls || ''}">${content}</${tag}>`;
}

function renderNavbar(comp: ComponentConfig, config: AppConfig, imageMap: Map<string, { blob: Blob; localPath: string }>, pages: PageConfig[]): string {
  const p = comp.props || {};
  const navItems = (p._nav_items as any[]) || [];
  const links = navItems.length > 0
    ? navItems.map((item: any) => {
        const href = item.link_type === "external" ? item.target : (item.link_type === "section" ? `#${item.target?.replace(/^#/, "")}` : `${item.target || "#"}.html`);
        const target = item.link_type === "external" && item.open_new_tab ? ' target="_blank"' : "";
        return `<a href="${href}" class="nav-link" data-editable data-edit-id="${eid()}"${target}>${item.label}</a>`;
      })
    : pages.filter(pg => pg.layout !== "dashboard").map((pg, i) => `<a href="${pg.route === "/" ? "index" : pg.route.replace(/^\//, "")}.html" class="nav-link${i === 0 ? " active" : ""}" data-editable data-edit-id="${eid()}">${pg.name}</a>`);

  return `<nav class="navbar">
  <div class="nav-logo">
    <div class="nav-logo-icon">${(p.logo_text || config.title || "R").charAt(0).toUpperCase()}</div>
    ${ed("span", p.logo_text || config.title || "Site")}
  </div>
  <div class="nav-links">${links.join("\n    ")}</div>
  <div class="flex items-center gap-2">
    ${ed("a", "Sign In", "btn btn-outline")}
    ${ed("a", "Get Started →", "btn btn-primary")}
  </div>
</nav>`;
}

function renderHero(comp: ComponentConfig, config: AppConfig): string {
  const p = comp.props || {};
  return `<section class="hero">
  <div class="container" style="max-width:640px;">
    ${ed("div", `✨ ${p.badge_text || "New Release"}`, "badge")}
    ${ed("h1", p.headline || config.title || "Build Something Amazing")}
    ${ed("p", p.subtitle || config.description || "The modern platform for building applications faster than ever.", "text-muted")}
    <div class="hero-actions">
      ${ed("a", `${p.cta_text || "Get Started"} →`, "btn btn-primary")}
      ${ed("a", "▶ Watch Demo", "btn btn-outline")}
    </div>
  </div>
</section>`;
}

function renderFooter(comp: ComponentConfig, config: AppConfig): string {
  const p = comp.props || {};
  const cols = [
    { title: "Product", links: ["Features", "Pricing", "Docs", "API"] },
    { title: "Company", links: ["About", "Blog", "Careers", "Press"] },
    { title: "Resources", links: ["Help Center", "Community", "Guides", "Tutorials"] },
    { title: "Legal", links: ["Privacy", "Terms", "Security", "Cookies"] },
  ];
  return `<footer class="footer">
  <div class="footer-grid">
    ${cols.map(c => `<div class="footer-col">
      ${ed("h4", c.title)}
      ${c.links.map(l => `<a href="#" data-editable data-edit-id="${eid()}">${l}</a>`).join("\n      ")}
    </div>`).join("\n    ")}
  </div>
  ${ed("div", `© ${new Date().getFullYear()} ${config.title || "Site"}. All rights reserved.`, "footer-bottom")}
</footer>`;
}

function renderStatsRow(comp: ComponentConfig): string {
  const metrics = [
    { label: "Total Revenue", value: "$45,231" },
    { label: "Active Users", value: "2,350" },
    { label: "Orders", value: "1,247" },
    { label: "Conversion", value: "3.24%" },
  ];
  return `<section class="section"><div class="container">
  <div class="stats-grid">
    ${metrics.map(m => `<div class="stat-card">
      ${ed("div", m.value, "stat-value")}
      ${ed("div", m.label, "stat-label")}
    </div>`).join("\n    ")}
  </div>
</div></section>`;
}

function renderFeaturesGrid(comp: ComponentConfig): string {
  const p = comp.props || {};
  const features = [
    { title: "Lightning Fast", desc: "Optimized for speed with instant load times and smooth interactions." },
    { title: "Secure by Default", desc: "Enterprise-grade security with encryption and access controls." },
    { title: "Easy Integration", desc: "Connect with your favorite tools through our powerful API." },
    { title: "Analytics Built-in", desc: "Track performance and user behavior with real-time dashboards." },
    { title: "24/7 Support", desc: "Expert support team available around the clock to help you." },
    { title: "Scalable", desc: "Grows with your business from startup to enterprise scale." },
  ];
  return `<section class="section"><div class="container">
  <div class="text-center" style="margin-bottom:40px;">
    <div class="badge">Features</div>
    ${ed("h2", p.title || "Everything You Need", "")}
    ${ed("p", p.subtitle || "Powerful features to help you build, launch, and grow.", "text-muted")}
  </div>
  <div class="grid grid-3" style="gap:20px;">
    ${features.map(f => `<div class="feature-card">
      <div class="feature-icon">⚡</div>
      ${ed("h3", f.title)}
      ${ed("p", f.desc, "text-sm text-muted")}
    </div>`).join("\n    ")}
  </div>
</div></section>`;
}

function renderPricingTable(comp: ComponentConfig): string {
  const plans = [
    { name: "Starter", price: "$0", period: "/month", features: ["5 projects", "1 GB storage", "Basic analytics", "Community support"], featured: false },
    { name: "Pro", price: "$29", period: "/month", features: ["Unlimited projects", "100 GB storage", "Advanced analytics", "Priority support", "Custom domains"], featured: true },
    { name: "Enterprise", price: "$99", period: "/month", features: ["Everything in Pro", "Unlimited storage", "SSO & SAML", "Dedicated account manager", "SLA guarantee", "Custom integrations"], featured: false },
  ];
  return `<section class="section"><div class="container">
  <div class="text-center" style="margin-bottom:40px;">
    ${ed("div", "Pricing", "badge")}
    ${ed("h2", "Simple, Transparent Pricing")}
    ${ed("p", "Choose the plan that's right for you.", "text-muted")}
  </div>
  <div class="pricing-grid">
    ${plans.map(p => `<div class="price-card${p.featured ? " featured" : ""}">
      ${ed("h3", p.name)}
      <div style="margin:20px 0;">${ed("span", p.price, "price-amount")}${ed("span", p.period, "price-period")}</div>
      <ul class="price-features">
        ${p.features.map(f => `<li data-editable data-edit-id="${eid()}">${f}</li>`).join("\n        ")}
      </ul>
      ${ed("a", "Get Started", `btn ${p.featured ? "btn-primary" : "btn-outline"} w-full justify-center`)}
    </div>`).join("\n    ")}
  </div>
</div></section>`;
}

function renderTestimonials(comp: ComponentConfig): string {
  const items = [
    { text: "This platform completely transformed how we build products. The speed and quality are unmatched.", name: "Sarah Johnson", role: "CEO, TechCorp" },
    { text: "We cut our development time by 60%. The AI features are incredibly powerful and intuitive.", name: "Michael Chen", role: "CTO, StartupX" },
    { text: "Best tool we've ever used. Our team productivity has skyrocketed since we switched.", name: "Emma Williams", role: "Lead Dev, DesignCo" },
  ];
  return `<section class="section" style="background:var(--bg-card);"><div class="container">
  <div class="text-center" style="margin-bottom:40px;">
    ${ed("div", "Testimonials", "badge")}
    ${ed("h2", "Loved by Teams Worldwide")}
  </div>
  <div class="grid grid-3" style="gap:20px;">
    ${items.map(t => `<div class="testimonial-card">
      ${ed("div", "★★★★★", "testimonial-stars")}
      ${ed("p", t.text, "text-sm")}
      <div class="testimonial-author">
        <div class="testimonial-avatar">${t.name.charAt(0)}</div>
        <div>
          ${ed("div", t.name, "font-medium text-sm")}
          ${ed("div", t.role, "text-xs text-muted")}
        </div>
      </div>
    </div>`).join("\n    ")}
  </div>
</div></section>`;
}

function renderFAQ(comp: ComponentConfig): string {
  const items = [
    { q: "How do I get started?", a: "Simply sign up for a free account and follow our quick-start guide. You'll be up and running in minutes." },
    { q: "Can I cancel anytime?", a: "Yes, you can cancel your subscription at any time. No long-term contracts or hidden fees." },
    { q: "Do you offer custom plans?", a: "Absolutely! Contact our sales team for custom enterprise solutions tailored to your needs." },
    { q: "What support options are available?", a: "We offer email support for all plans, with priority and dedicated support for Pro and Enterprise users." },
  ];
  return `<section class="section"><div class="container" style="max-width:700px;">
  <div class="text-center" style="margin-bottom:40px;">
    ${ed("div", "FAQ", "badge")}
    ${ed("h2", "Frequently Asked Questions")}
  </div>
  ${items.map(item => `<div class="faq-item">
    <button class="faq-question" onclick="this.parentElement.classList.toggle('open');this.nextElementSibling.style.display=this.nextElementSibling.style.display==='block'?'none':'block';">
      <span data-editable data-edit-id="${eid()}">${item.q}</span>
      <span>+</span>
    </button>
    ${ed("div", item.a, "faq-answer")}
  </div>`).join("\n  ")}
</div></section>`;
}

function renderFinalCTA(comp: ComponentConfig): string {
  const p = comp.props || {};
  return `<section style="padding:40px 24px;"><div class="cta-section">
  ${ed("h2", p.headline || "Ready to Get Started?")}
  ${ed("p", p.subtitle || "Join thousands of teams already building with our platform.")}
  ${ed("a", `${p.cta_text || "Start Free Trial"} →`, "btn")}
</div></section>`;
}

function renderContactForm(comp: ComponentConfig): string {
  return `<section class="section"><div class="container" style="max-width:600px;">
  <div class="text-center" style="margin-bottom:32px;">
    ${ed("div", "Contact", "badge")}
    ${ed("h2", "Get in Touch")}
    ${ed("p", "We'd love to hear from you. Send us a message!", "text-muted")}
  </div>
  <form class="contact-form mx-auto" onsubmit="event.preventDefault();alert('Message sent!');">
    <div class="grid grid-2" style="gap:16px;">
      <div class="form-group">${ed("label", "Name", "form-label")}<input class="input" placeholder="Your name" /></div>
      <div class="form-group">${ed("label", "Email", "form-label")}<input class="input" type="email" placeholder="you@example.com" /></div>
    </div>
    <div class="form-group">${ed("label", "Subject", "form-label")}<input class="input" placeholder="How can we help?" /></div>
    <div class="form-group">${ed("label", "Message", "form-label")}<textarea class="input" rows="4" placeholder="Your message..."></textarea></div>
    ${ed("button", "Send Message", "btn btn-primary w-full justify-center")}
  </form>
</div></section>`;
}

function renderNewsletterCTA(comp: ComponentConfig): string {
  const p = comp.props || {};
  return `<section class="section" style="background:var(--bg-card);"><div class="container text-center" style="max-width:500px;">
  ${ed("h2", p.headline || "Stay Updated")}
  ${ed("p", p.subtitle || "Subscribe to our newsletter for the latest updates.", "text-muted")}
  <form onsubmit="event.preventDefault();alert('Subscribed!');" class="flex gap-2 justify-center" style="margin-top:20px;">
    <input class="input" style="max-width:300px;" placeholder="Enter your email" type="email" />
    ${ed("button", "Subscribe", "btn btn-primary")}
  </form>
</div></section>`;
}

function renderCardGrid(comp: ComponentConfig): string {
  const cards = [
    { title: "Getting Started", desc: "Quick setup guide to launch your first project in minutes." },
    { title: "API Reference", desc: "Complete API documentation with code examples and guides." },
    { title: "Best Practices", desc: "Learn the recommended patterns and workflows for success." },
  ];
  return `<section class="section"><div class="container">
  <div class="grid grid-3" style="gap:20px;">
    ${cards.map(c => `<div class="card">
      ${ed("h3", c.title)}
      ${ed("p", c.desc, "text-sm text-muted")}
      ${ed("a", "Learn More →", "btn btn-outline")}
    </div>`).join("\n    ")}
  </div>
</div></section>`;
}

function renderTeamSection(comp: ComponentConfig): string {
  const members = [
    { name: "Alex Rivera", role: "CEO & Founder" },
    { name: "Sarah Chen", role: "CTO" },
    { name: "Mike Johnson", role: "Head of Design" },
    { name: "Emily Davis", role: "Lead Engineer" },
  ];
  return `<section class="section"><div class="container">
  <div class="text-center" style="margin-bottom:40px;">
    ${ed("div", "Team", "badge")}
    ${ed("h2", "Meet Our Team")}
  </div>
  <div class="grid grid-4" style="gap:24px;">
    ${members.map(m => `<div class="text-center">
      <div class="testimonial-avatar mx-auto" style="width:64px;height:64px;font-size:1.25rem;margin-bottom:12px;">${m.name.charAt(0)}</div>
      ${ed("h3", m.name, "text-sm")}
      ${ed("div", m.role, "text-xs text-muted")}
    </div>`).join("\n    ")}
  </div>
</div></section>`;
}

function renderBlogPreview(comp: ComponentConfig): string {
  const posts = [
    { title: "Getting Started with Our Platform", excerpt: "A comprehensive guide to setting up your first project.", date: "Jan 15, 2024" },
    { title: "Best Practices for Modern Development", excerpt: "Learn the patterns and workflows used by top teams.", date: "Jan 10, 2024" },
    { title: "What's New in Version 2.0", excerpt: "Explore the exciting new features and improvements.", date: "Jan 5, 2024" },
  ];
  return `<section class="section"><div class="container">
  <div class="text-center" style="margin-bottom:40px;">
    ${ed("div", "Blog", "badge")}
    ${ed("h2", "Latest Articles")}
  </div>
  <div class="grid grid-3" style="gap:20px;">
    ${posts.map(p => `<div class="card">
      ${ed("div", p.date, "text-xs text-muted")}
      ${ed("h3", p.title)}
      ${ed("p", p.excerpt, "text-sm text-muted")}
      ${ed("a", "Read More →", "")}
    </div>`).join("\n    ")}
  </div>
</div></section>`;
}

function renderGenericComponent(comp: ComponentConfig): string {
  return `<section class="section"><div class="container">
  <div class="card text-center">
    ${ed("h3", comp.type.replace(/_/g, " "))}
    ${ed("p", "This component is rendered as a placeholder in the static export.", "text-sm text-muted")}
  </div>
</div></section>`;
}

// ── Component Router ────────────────────────────────────────

function renderComponent(comp: ComponentConfig, config: AppConfig, imageMap: Map<string, { blob: Blob; localPath: string }>, pages: PageConfig[]): string {
  switch (comp.type) {
    case "navbar": return renderNavbar(comp, config, imageMap, pages);
    case "hero": return renderHero(comp, config);
    case "footer": return renderFooter(comp, config);
    case "stats_row": return renderStatsRow(comp);
    case "features_grid": return renderFeaturesGrid(comp);
    case "pricing_table": return renderPricingTable(comp);
    case "testimonials": return renderTestimonials(comp);
    case "faq": return renderFAQ(comp);
    case "final_cta": return renderFinalCTA(comp);
    case "contact_form": return renderContactForm(comp);
    case "newsletter_cta": return renderNewsletterCTA(comp);
    case "card_grid": return renderCardGrid(comp);
    case "team_section": return renderTeamSection(comp);
    case "blog_preview": return renderBlogPreview(comp);
    default: return renderGenericComponent(comp);
  }
}

// ── Page → HTML ─────────────────────────────────────────────

function generatePageHTML(page: PageConfig, config: AppConfig, imageMap: Map<string, { blob: Blob; localPath: string }>, pages: PageConfig[], cssPath: string, jsPath: string): string {
  editCounter = 0;
  const components = page.components.map(c => renderComponent(c, config, imageMap, pages)).join("\n\n");
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${page.name} — ${config.title || "Site"}</title>
  <meta name="description" content="${config.description || ""}" />
  <link rel="stylesheet" href="${cssPath}" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
</head>
<body>
${components}
<script src="${jsPath}"><\/script>
</body>
</html>`;
}

// ── Main Export Function ────────────────────────────────────

export interface HTMLExportResult {
  blob: Blob;
  filename: string;
  pageCount: number;
  imageCount: number;
}

function generatePassword(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789";
  const arr = new Uint8Array(12);
  crypto.getRandomValues(arr);
  return Array.from(arr, (b) => chars[b % chars.length]).join("");
}

export async function exportToHTML(config: AppConfig, onProgress?: (msg: string) => void): Promise<HTMLExportResult> {
  const zip = new JSZip();
  const slug = config.title?.toLowerCase().replace(/\s+/g, "-") || "project";

  // Auto-generate a unique password for each download
  const password = generatePassword();

  onProgress?.("Collecting images...");
  const imageUrls = collectImageUrls(config);
  const imageMap = await downloadImages(imageUrls);

  onProgress?.("Generating CSS...");
  zip.file("css/styles.css", generateCSS(config));

  onProgress?.("Generating editor...");
  zip.file("js/editor.js", generateEditorJS(password));

  // Store password in editor.txt for the owner
  zip.file("editor.txt", `========================================
  EDITOR PASSWORD — KEEP THIS PRIVATE
========================================

Project: ${config.title || "Untitled"}
Generated: ${new Date().toISOString()}

Password: ${password}

========================================
HOW TO USE:
========================================
1. Open any HTML page in your browser
2. Press Ctrl+Shift+E to open the editor login
3. Enter the password above
4. The Live Editor toolbar will appear
5. Click text to edit, click images to replace
6. Use "Save" to persist, "Lock" to hide editor

NOTE: The editor is completely hidden from
visitors. Only you (the owner) can activate
it using the keyboard shortcut + password.

⚠️ Do NOT upload this file to your server!
========================================
`);

  // Add downloaded images
  onProgress?.(`Bundling ${imageMap.size} images...`);
  for (const [, { blob, localPath }] of imageMap) {
    zip.file(localPath, blob);
  }

  // Generate HTML pages
  const pages = config.pages.filter(p => p.layout !== "dashboard" || config.pages.length === 1);
  onProgress?.(`Generating ${pages.length} page(s)...`);

  for (const page of pages) {
    const filename = page.route === "/" ? "index.html" : `${page.route.replace(/^\//, "").replace(/\//g, "-")}.html`;
    const html = generatePageHTML(page, config, imageMap, pages, "css/styles.css", "js/editor.js");
    zip.file(filename, html);
  }

  // Add a README
  zip.file("README.md", [
    `# ${config.title || "Project"}`,
    "",
    config.description || "",
    "",
    "Generated by **RyaanCMS AI Builder**",
    "",
    "## Files",
    `- \`*.html\` — Page files (${pages.length} pages)`,
    "- `css/styles.css` — All styles",
    "- `js/editor.js` — Inline content editor (password-protected)",
    "- `editor.txt` — Editor password (DO NOT upload to server!)",
    `- \`images/\` — Downloaded images (${imageMap.size} files)`,
    "",
    "## Editing",
    "1. Upload all files **except editor.txt** to your web server",
    "2. Open any HTML page in a browser",
    "3. Press **Ctrl+Shift+E** to open the editor login prompt",
    "4. Enter the password from `editor.txt`",
    "5. Edit text, replace images, save changes",
    "",
    "## Notes",
    "- The editor is completely hidden from visitors",
    "- Only the owner with the password can activate the editor",
    "- Changes are saved to browser localStorage",
    '- Use "Lock" button to hide the editor again',
  ].join("\n"));

  onProgress?.("Creating ZIP...");
  const blob = await zip.generateAsync({ type: "blob" });

  return {
    blob,
    filename: `${slug}-html.zip`,
    pageCount: pages.length,
    imageCount: imageMap.size,
  };
}
