// ============================================================
// Theme & Branding Generator
// Dynamic CSS variable generation for multi-theme support
// ============================================================

import type { StyleConfig } from "./component-registry";

export interface BrandingTokens {
  name: string;
  primary_color: string; // hex
  accent_color?: string;
  font: string;
  border_radius: string;
  theme_mode: "light" | "dark" | "auto";
}

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  tokens: BrandingTokens;
}

export interface GeneratedTheme {
  preset_name: string;
  css_variables: string;
  tailwind_config_patch: Record<string, any>;
  tokens: BrandingTokens;
}

// === Built-in Theme Presets ===

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "saas_clean",
    name: "SaaS Clean",
    description: "Modern SaaS with indigo primary and clean whites",
    tokens: { name: "SaaS Clean", primary_color: "#6366f1", accent_color: "#8b5cf6", font: "Inter", border_radius: "0.75rem", theme_mode: "auto" },
  },
  {
    id: "corporate_blue",
    name: "Corporate Blue",
    description: "Professional corporate with blue tones",
    tokens: { name: "Corporate Blue", primary_color: "#2563eb", accent_color: "#3b82f6", font: "Inter", border_radius: "0.5rem", theme_mode: "light" },
  },
  {
    id: "startup_gradient",
    name: "Startup Gradient",
    description: "Bold startup look with vibrant purple-pink",
    tokens: { name: "Startup Gradient", primary_color: "#8b5cf6", accent_color: "#ec4899", font: "Inter", border_radius: "1rem", theme_mode: "auto" },
  },
  {
    id: "dark_neon",
    name: "Dark Neon",
    description: "Dark theme with neon green accent",
    tokens: { name: "Dark Neon", primary_color: "#10b981", accent_color: "#06d6a0", font: "Inter", border_radius: "0.75rem", theme_mode: "dark" },
  },
  {
    id: "minimal_mono",
    name: "Minimal Mono",
    description: "Minimalist monochrome design",
    tokens: { name: "Minimal Mono", primary_color: "#18181b", accent_color: "#71717a", font: "Inter", border_radius: "0.375rem", theme_mode: "light" },
  },
  {
    id: "warm_sunset",
    name: "Warm Sunset",
    description: "Warm tones with orange-amber accent",
    tokens: { name: "Warm Sunset", primary_color: "#ea580c", accent_color: "#f59e0b", font: "Inter", border_radius: "0.75rem", theme_mode: "auto" },
  },
];

// === Hex to HSL Conversion ===

function hexToHSL(hex: string): { h: number; s: number; l: number } {
  hex = hex.replace("#", "");
  const r = parseInt(hex.substring(0, 2), 16) / 255;
  const g = parseInt(hex.substring(2, 4), 16) / 255;
  const b = parseInt(hex.substring(4, 6), 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
      case g: h = ((b - r) / d + 2) / 6; break;
      case b: h = ((r - g) / d + 4) / 6; break;
    }
  }

  return { h: Math.round(h * 360), s: Math.round(s * 100), l: Math.round(l * 100) };
}

// === Generator ===

export function generateTheme(tokens: BrandingTokens): GeneratedTheme {
  const primary = hexToHSL(tokens.primary_color);
  const accent = tokens.accent_color ? hexToHSL(tokens.accent_color) : { h: (primary.h + 30) % 360, s: primary.s, l: primary.l };

  const radiusMap: Record<string, string> = {
    "none": "0",
    "sm": "0.25rem",
    "md": "0.5rem",
    "lg": "0.75rem",
    "full": "9999px",
  };
  const radius = radiusMap[tokens.border_radius] || tokens.border_radius;

  const css_variables = generateCSSVariables(primary, accent, radius, tokens);

  const tailwind_config_patch = {
    theme: {
      extend: {
        fontFamily: { sans: [tokens.font, "system-ui", "sans-serif"] },
        borderRadius: { DEFAULT: radius },
      },
    },
  };

  return {
    preset_name: tokens.name,
    css_variables,
    tailwind_config_patch,
    tokens,
  };
}

function generateCSSVariables(
  primary: { h: number; s: number; l: number },
  accent: { h: number; s: number; l: number },
  radius: string,
  tokens: BrandingTokens
): string {
  // Generate complementary colors
  const primaryFg = primary.l > 50 ? "0 0% 0%" : "0 0% 100%";
  const accentFg = `${accent.h} ${accent.s}% ${Math.max(accent.l - 30, 10)}%`;

  return `/* ============================================
   Theme: ${tokens.name}
   Generated by RyaanCMS Theme Generator
   ============================================ */

:root {
  /* Primary */
  --primary: ${primary.h} ${primary.s}% ${primary.l}%;
  --primary-foreground: ${primaryFg};

  /* Accent */
  --accent: ${accent.h} ${Math.min(accent.s, 40)}% ${Math.min(accent.l + 40, 97)}%;
  --accent-foreground: ${accent.h} ${accent.s}% ${accent.l}%;

  /* Ring */
  --ring: ${primary.h} ${primary.s}% ${primary.l}%;

  /* Radius */
  --radius: ${radius};

  /* Gradients */
  --gradient-primary: linear-gradient(135deg, hsl(${primary.h} ${primary.s}% ${primary.l}%), hsl(${accent.h} ${accent.s}% ${accent.l}%));
  --shadow-primary: 0 8px 32px hsl(${primary.h} ${primary.s}% ${primary.l}% / 0.2);
  --shadow-glow: 0 0 60px hsl(${primary.h} ${primary.s}% ${primary.l}% / 0.15);
}

.dark {
  /* Primary (lightened for dark mode) */
  --primary: ${primary.h} ${primary.s}% ${Math.min(primary.l + 10, 75)}%;
  --primary-foreground: 0 0% 100%;

  /* Accent (darkened for dark mode) */
  --accent: ${accent.h} ${Math.min(accent.s, 40)}% ${Math.max(accent.l - 30, 16)}%;
  --accent-foreground: ${accent.h} ${accent.s}% ${Math.min(accent.l + 20, 75)}%;

  /* Ring */
  --ring: ${primary.h} ${primary.s}% ${Math.min(primary.l + 10, 75)}%;

  /* Gradients */
  --gradient-primary: linear-gradient(135deg, hsl(${primary.h} ${primary.s}% ${Math.max(primary.l - 5, 40)}%), hsl(${accent.h} ${accent.s}% ${Math.max(accent.l - 10, 35)}%));
  --shadow-primary: 0 8px 32px hsl(${primary.h} ${primary.s}% ${primary.l}% / 0.3);
  --shadow-glow: 0 0 80px hsl(${primary.h} ${primary.s}% ${primary.l}% / 0.2);
}`;
}

export function getThemePreset(id: string): ThemePreset | undefined {
  return THEME_PRESETS.find((t) => t.id === id);
}

export function generateThemeFromStyle(style: StyleConfig): GeneratedTheme {
  const tokens: BrandingTokens = {
    name: "Custom",
    primary_color: style.primary_color || "#6366f1",
    font: style.font || "Inter",
    border_radius: style.border_radius || "lg",
    theme_mode: style.theme || "auto",
  };
  return generateTheme(tokens);
}
