import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const token = authHeader.replace("Bearer ", "");
    const { data: claimsData, error: claimsError } = await supabase.auth.getClaims(token);
    if (claimsError || !claimsData?.claims) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const { repo, config, sql, readme } = await req.json();

    if (!repo) {
      return new Response(JSON.stringify({ error: "Repository name required" }), { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const githubToken = Deno.env.get("GITHUB_TOKEN");
    if (!githubToken) {
      return new Response(JSON.stringify({ error: "GITHUB_TOKEN not configured" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const [owner, repoName] = repo.includes("/") ? repo.split("/") : [null, repo];

    // Get authenticated user if no owner specified
    let repoOwner = owner;
    if (!repoOwner) {
      const userRes = await fetch("https://api.github.com/user", {
        headers: { Authorization: `Bearer ${githubToken}`, Accept: "application/vnd.github.v3+json" },
      });
      if (!userRes.ok) {
        return new Response(JSON.stringify({ error: "Failed to authenticate with GitHub" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      }
      const ghUser = await userRes.json();
      repoOwner = ghUser.login;
    }

    const fullRepo = `${repoOwner}/${repoName}`;

    // Check if repo exists, create if not
    const repoCheckRes = await fetch(`https://api.github.com/repos/${fullRepo}`, {
      headers: { Authorization: `Bearer ${githubToken}`, Accept: "application/vnd.github.v3+json" },
    });

    if (repoCheckRes.status === 404) {
      const createRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: "application/vnd.github.v3+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: repoName,
          description: `Generated by RyaanCMS AI Builder`,
          private: false,
          auto_init: true,
        }),
      });
      if (!createRes.ok) {
        const err = await createRes.json();
        return new Response(JSON.stringify({ error: `Failed to create repo: ${err.message}` }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      }
      // Wait for repo initialization
      await new Promise((r) => setTimeout(r, 2000));
    }

    // Push files using the Contents API
    const files: { path: string; content: string }[] = [
      { path: "config.json", content: config || "{}" },
      { path: "schema.sql", content: sql || "" },
      { path: "README.md", content: readme || `# ${repoName}\n\nGenerated by RyaanCMS AI Builder` },
      { path: ".ryaancms/metadata.json", content: JSON.stringify({ generator: "RyaanCMS AI Builder", version: "1.0.0", generated_at: new Date().toISOString() }, null, 2) },
    ];

    const pushed: string[] = [];

    for (const file of files) {
      // Check if file exists to get SHA for update
      let sha: string | undefined;
      const existRes = await fetch(`https://api.github.com/repos/${fullRepo}/contents/${file.path}`, {
        headers: { Authorization: `Bearer ${githubToken}`, Accept: "application/vnd.github.v3+json" },
      });
      if (existRes.ok) {
        const existData = await existRes.json();
        sha = existData.sha;
      }

      const putRes = await fetch(`https://api.github.com/repos/${fullRepo}/contents/${file.path}`, {
        method: "PUT",
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: "application/vnd.github.v3+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: `${sha ? "Update" : "Add"} ${file.path} via RyaanCMS AI Builder`,
          content: btoa(unescape(encodeURIComponent(file.content))),
          ...(sha ? { sha } : {}),
        }),
      });

      if (putRes.ok) {
        pushed.push(file.path);
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        repo: fullRepo,
        url: `https://github.com/${fullRepo}`,
        files_pushed: pushed,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err: any) {
    return new Response(
      JSON.stringify({ error: err.message || "Internal error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
